name: validate-article

on:
  pull_request:
    branches:
      - main
    paths:
      - "_posts/**.md"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate-article.ps1
        shell: pwsh
        run: ./scripts/validate-article.ps1
